sudo: false

language: node_js
os:
#  - linux # turned off until we can figure out why it is only failing on linux
  - osx
node_js:
  - "node"
  - "12"
  - "10"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - npm install
  - npm test
  - npm run test-client-integration
