sudo: false

language: node_js
os:
  - linux
  - osx
node_js:
  # Node 11 is turned off  because it blocks building until a security issue with node-sass is fixed.
  # - "node"
  - "10"
  - "8"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - npm install
  - npm test
  - npm run test-client-integration
